# Generated by Django 5.1.7 on 2025-04-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_listing_owns'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.BigIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='listing_images/'),
        ),
    ]
